### PR TITLE
Fix bool IValues on iOS

### PR DESCRIPTION
**Pull request by iceychris**

### CODE REVIEW

**Review by Legion2 — APPROVED** [review]

**Comment by erksch** [comment]
Which problem was fixed here? :)

**Comment by Legion2** [comment]
The name of the interop boolean constructor was wrong.

**Comment by erksch** [comment]
Can you elaborate? The tests added here also pass without changing the Obj-C API

**Comment by Legion2** [comment]
This may be a caching issue

**Comment by erksch** [comment]
The added simulator tests pass without changing as confirmed in the CI in #26.
Closing in favor of #26

**Pull request closed without merging**
