### PR TITLE
Add iosSimulatorArm64 target

### PR DESCRIPTION
**Pull request by erksch**
To add the arm64 simulator target we need to

- [x] Build LibTorch-Lite from source for iOS Arm simulator
- [x] Distribute LibTorch-Lite as an xcframework instead of a fat (x64, arm64) libs (via https://github.com/voize-gmbh/pytorch-lite-builds)
- [x] add iosSimulatorArm64 target
- [x] Remove FS dependency as it does not work for the `iosSimulatorArm64` target, replace with Okio
- [x] Add CI for arm64 simulator tests

### CODE REVIEW

**Comment by alexandru-g** [comment]
@erksch I've tried adding iosSimulatorArm64 support using your changes but I can't get our iOS project to compile for the simulator, only physical devices seem to work. Did you notice anything similar?

**Comment by erksch** [comment]
@alexandru-g Thank you for trying it out! We have not really tested this branch yet. 
We should add ARM simulator like the X86 simulator test to verify that the changes work.

**Comment by alexandru-g** [comment]
Unfortunately even the base LibTorch-Lite library doesn't play nice with the arm64 simulator. It needs to be compiled specifically for it.

**Comment by erksch** [comment]
Indeed when trying to just compile with the standard PyTorch Arm64 lib I get the following error:

```
ld: building for 'iOS-simulator', but linking in object file (/Users/erik/voize/pytorch-lite-multiplatform/build/cocoapods/synthetic/IOS/Pods/LibTorch-Lite/install/lib/libc10.a[arm64][2](Allocator.cpp.o)) built for 'iOS'
```

**Comment by erksch** [comment]
Can not do a build locally due to https://youtrack.jetbrains.com/issue/KT-65542/Cinterop-tasks-fails-if-Xcode-15.3-is-used

**Review by iceychris — APPROVED** [review]

**Pull request merged**
